export { default as About } from "./About"
export { default as Blogs } from "./Blogs"
export { default as Contact } from "./Contact"
export { default as Work } from "./Work"
export { default as Works } from "./Works"
