export { default as BlogCard } from "./shared/BlogCard"
export { default as Card } from "./shared/Card"
export { default as ErrorFallback } from "./shared/ErrorFallback"
export { default as Footer } from "./shared/Footer"
export { default as Illustration } from "./shared/Illustration"
export { default as Image } from "./shared/Image"
export { default as Input } from "./shared/Input"
export { default as Loader } from "./shared/Loader"
export { default as Navbar } from "./shared/Navbar"
export { default as Pagination } from "./shared/Pagination"
export { default as Spinner } from "./shared/Spinner"
export { default as WorkCard } from "./shared/WorkCard"

//layouts
export { default as MainLayout } from "./layouts/Main"
