import type { ProjectProps } from "types"

import {
	chatt,
	ebaba,
	koin,
	nexus,
	olonagirl,
	onboard,
	three_shirt,
	traxo,
	traxo_hq,
	tsl,
	zummit_ai,
} from "assets/images"

export const projects: ProjectProps[] = [
	{
		id: "dba68196-100c-4043-89b9-911aebdf65ae",
		title: "Olonagirl",
		subtitle: "",
		image: [olonagirl],
		url: "https://olonagirl.vercel.app/",
		category: "e-commerce website",
		color: "#FFEA00",
		stacks: ["nextjs", "tailwind", "framer-motion", "commercejs"],
		meta: {
			title: "Afro-fashion at it's finest. Celebrating and promoting the Afro-fashion movement.",
			client: "Olonagirl",
			sector: "e-commerce",
			description:
				"Olonagirl is a platform to buy and sell clothes online. It is a platform that connects people to buy and sell clothes, and helps them to find the right clothes for them.",
			year: "2023",
		},
	},
	{
		id: "e11dcef1-1103-46d8-80c8-94a30cf823d7",
		title: "Zummit Africa",
		subtitle: "",
		image: [zummit_ai],
		url: "https://development.d23rav6l6c7mra.amplifyapp.com/",
		category: "website",
		color: "#FFEA00",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title: "Building the next generaton of African tech giants.",
			client: "Zummit Africa",
			sector: "sftware developement",
			description: "Zummit Africa is a ",
			year: "2023",
		},
	},
	{
		id: "387d3954-c2ea-4186-a31f-e9e39fd0c78c",
		title: "Onboard",
		subtitle: "",
		image: [onboard],
		url: "https://onboard.com.ng",
		category: "website",
		color: "#6FA7B4",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title: "Trusted partner in travels.",
			client: "Onboard",
			sector: "travel",
			description: "Onboard is a platform that helps people to book travels, hotels and .",
			year: "2022",
		},
	},
	{
		id: "d68841fd-d639-4a53-b9c5-e8ca37ef510a",
		title: "Traxo Finance",
		subtitle: "",
		image: [traxo],
		url: "https://master.d16z9rxqclx4lm.amplifyapp.com/",
		category: "digital product",
		color: "#151515",
		stacks: ["react", "tailwind", "headless UI", "vite"],
		meta: {
			title: "A financial platform that allows users to invest in cryptocurrencies.",
			client: "Traxo Finance",
			sector: "finance",
			description:
				"Traxo Finance is a financial platform that allows users to invest in cryptocurrencies. It is a platform that allows users to invest in cryptocurrencies and earn rewards. It is a platform that allows users to invest in cryptocurrencies and earn rewards.",
			year: "2021",
		},
	},
	{
		id: "",
		title: "TraxoHQ",
		subtitle: "",
		image: [traxo_hq],
		url: "https://traxo-hq.vercel.app",
		category: "website",
		color: "#20DA91",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title: "",
			client: "",
			sector: "Education",
			description: "",
			year: "2023",
		},
	},
	{
		id: "aba25bc6-2e78-432b-aa4c-430e9d95e0b7",
		title: "Koin",
		subtitle: "",
		image: [koin],
		url: "https://koin-token.vercel.app",
		category: "website",
		color: "#6366F1",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title:
				"A cryptocurrency that allows users to exchange their cryptocurrencies for other cryptocurrencies.",
			client: "Koin",
			sector: "e-commerce",
			description:
				"Koin is a cryptocurrency that allows users to exchange their cryptocurrencies for other cryptocurrencies. It is a cryptoc",
			year: "2021",
		},
	},
	{
		id: "54aa9973-0f32-4dff-8075-936425b14070",
		title: "Chatt",
		subtitle: "",
		image: [chatt],
		url: "https://chatt-mu.vercel.app",
		category: "website",
		color: "#3B82F6",
		stacks: ["react", "tailwind", "vite"],
		meta: {
			title: "Free messaging. VoIP and video calling. Connect seamlessly with friends and family.",
			client: "Chatt",
			sector: "software",
			description:
				"Chatt is a messaging app that allows users to chat with friends and family using voice or video calling.",
			year: "2021",
		},
	},
	{
		id: "88feedc7-7167-4284-8db5-7ed1bf0f22e4",
		title: "Three-Shirt",
		subtitle: "",
		image: [three_shirt],
		url: "https://3-shirt.vercel.app",
		category: "website",
		color: "#CDCDCD",
		stacks: ["react", "tailwind", "framer-motion", "threejs", "vite"],
		meta: {
			title: "Need a fast mockup for your next project? No problem.",
			client: "side project",
			sector: "software",
			description:
				"Three-Shirt is a website that allows users to create mockups of shirts. It allows adding logo, text, and images to your mockup.",
			year: "2021",
		},
	},
	// {
	// 	id: "b7133a22-8755-4487-bb73-98f7c60addfc",
	// 	title: "Admin Dashboard",
	// 	subtitle: "",
	// 	image: [dashboard],
	// 	url: "https://c-dashboard.vercel.app",
	// 	category: "website",
	// 	color: "#FB9678",
	// 	stacks: ["react", "tailwind", "syncfusion", "vite"],
	// 	meta: {
	// 		title: "",
	// 		client: "",
	// 		sector: "",
	// 		description: "",
	// 		year: "",
	// 	}
	// },
	{
		id: "27e5f209-5a6a-456a-bd6f-5289bb149744",
		title: "TSL",
		subtitle: "",
		image: [tsl],
		url: "https://tech-solutions.vercel.app",
		category: "website",
		color: "#FE0807",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title: "Affordable logistics solutions.",
			client: "TSL",
			sector: "logistics",
			description:
				"TSL is a logistics solutions for small and medium businesses. They help businesses to send and receive goods between Europe, Asia, the Americas and Africa. They have fast and reliable delivery services.",
			year: "2023",
		},
	},
	{
		id: "b3a99d3b-149e-4f53-9422-0f3c8b740aa4",
		title: "ebaba",
		subtitle: "",
		image: [ebaba],
		url: "https://ebaba-gray.vercel.app/",
		category: "website",
		color: "#1E2746",
		stacks: ["react", "tailwind", "vite"],
		meta: {
			title: "Get professionals without hassle.",
			client: "ebaba",
			sector: "e-commerce",
			description:
				"Ebaba helps connect users to professionals with the right skills and experience. It helps users to find the right professionals for their needs.",
			year: "2022",
		},
	},
	// {
	// 	id: "c80ccf01-4355-401e-b0f6-8abbf8d2e47d",
	// 	title: "Threejs Shaders",
	// 	subtitle: "",
	// 	image: [threejs_shaders],
	// 	url: "https://threejs-shaders-rgb-effect.vercel.app/",
	// 	category: "website",
	// 	color: "#394C6E",
	// 	stacks: ["react", "tailwind", "framer-motion"],
	// 	meta: {
	// 		title:
	// 			"I love art. And web development. I love shaders. So I made this website to share them with the world.",
	// 		client: "Side Project",
	// 		sector: "art",
	// 		description: "A collection of art made with Threejs shaders.",
	// 		year: "2021",
	// 	},
	// },
	{
		id: "fda6c4ce-1b05-4580-bc6f-491a946db4a1",
		title: "Nexus",
		subtitle: "",
		image: [nexus],
		url: "https://nexus-llc.vercel.app/",
		category: "digital product",
		color: "#3A53E4",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
		meta: {
			title: "Discover APIs. Monitize your projects. Automate your workflows.",
			client: "Side Project",
			sector: "software",
			description:
				"Nexus is a marketplace for APIs. It allows users to discover APIs, monitize their projects, and automate subscriptions, users, and projects workflows.",
			year: "2023",
		},
	},
]
