import type { ProjectProps } from "types"

import {
	chatt,
	dashboard,
	ebaba,
	koin,
	nexus,
	olonagirl,
	onboard,
	threejs_shaders,
	three_shirt,
	traxo,
	tsl,
	zummit_ai,
} from "assets/images"

export const projects: ProjectProps[] = [
	{
		id: "dba68196-100c-4043-89b9-911aebdf65ae",
		title: "Olonagirl",
		image: [olonagirl],
		url: "https://olonagirl.vercel.app/",
		category: "e-commerce website",
		color: "#FFEA00",
		stacks: ["nextjs", "tailwind", "framer-motion", "commercejs"],
	},
	{
		id: "e11dcef1-1103-46d8-80c8-94a30cf823d7",
		title: "Zummit Africa",
		image: [zummit_ai],
		url: "https://development.d23rav6l6c7mra.amplifyapp.com/",
		category: "website",
		color: "#FFEA00",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
	},
	{
		id: "d68841fd-d639-4a53-b9c5-e8ca37ef510a",
		title: "Traxo Finance",
		image: [traxo],
		url: "https://master.d16z9rxqclx4lm.amplifyapp.com/",
		category: "digital product",
		color: "#151515",
		stacks: ["react", "tailwind", "headless ui", "vite"],
	},
	{
		id: "387d3954-c2ea-4186-a31f-e9e39fd0c78c",
		title: "Onboard",
		image: [onboard],
		url: "https://onboard.com.ng",
		category: "website",
		color: "#6FA7B4",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
	},
	{
		id: "aba25bc6-2e78-432b-aa4c-430e9d95e0b7",
		title: "Koin",
		image: [koin],
		url: "https://koin-token.vercel.app",
		category: "website",
		color: "#6366F1",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
	},
	{
		id: "54aa9973-0f32-4dff-8075-936425b14070",
		title: "Chatt",
		image: [chatt],
		url: "https://chatt-mu.vercel.app",
		category: "website",
		color: "#3B82F6",
		stacks: ["react", "tailwind", "vite"],
	},
	{
		id: "88feedc7-7167-4284-8db5-7ed1bf0f22e4",
		title: "Three-Shirt",
		image: [three_shirt],
		url: "https://3-shirt.vercel.app",
		category: "website",
		color: "#CDCDCD",
		stacks: ["react", "tailwind", "framer-motion", "threejs", "vite"],
	},
	{
		id: "b7133a22-8755-4487-bb73-98f7c60addfc",
		title: "Admin Dashboard",
		image: [dashboard],
		url: "https://c-dashboard.vercel.app",
		category: "website",
		color: "#FB9678",
		stacks: ["react", "tailwind", "syncfusion", "vite"],
	},
	{
		id: "27e5f209-5a6a-456a-bd6f-5289bb149744",
		title: "TSL",
		image: [tsl],
		url: "https://tech-solutions.vercel.app",
		category: "website",
		color: "#FE0807",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
	},
	{
		id: "b3a99d3b-149e-4f53-9422-0f3c8b740aa4",
		title: "ebaba",
		image: [ebaba],
		url: "https://ebaba-gray.vercel.app/",
		category: "website",
		color: "#1E2746",
		stacks: ["react", "tailwind", "vite"],
	},
	{
		id: "c80ccf01-4355-401e-b0f6-8abbf8d2e47d",
		title: "Threejs Shaders",
		image: [threejs_shaders],
		url: "https://threejs-shaders-rgb-effect.vercel.app/",
		category: "website",
		color: "#394C6E",
		stacks: ["react", "tailwind", "framer-motion"],
	},
	{
		id: "fda6c4ce-1b05-4580-bc6f-491a946db4a1",
		title: "Nexus",
		image: [nexus],
		url: "https://nexus-llc.vercel.app/",
		category: "digital product",
		color: "#3A53E4",
		stacks: ["react", "tailwind", "framer-motion", "vite"],
	},
]
